[plugin]
repository = "https://github.com/SheepGoMeh/VisibilityPlugin.git"
owners = [ "SheepGoMeh",]
project_path = "Visibility"
commit = "9bfa7dbd9bbf254f759491acec326cef9dbb3f43"
changelog = "- Updated plugin for 7.2"
